variables:
-   name: environment
    value: dev

-   name: azureSubscription
    value: dev-service-connection

-   name: faName
    value: function-name-fa

-   name: faSettings
    value: >-
        -sample-key sample-value
